version: '3'
services:
  rag-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./persistent_storage:/app/persistent_storage
      - ./data:/app/data
      - ./.streamlit:/app/.streamlit
